image: archlinux
packages:
  - rust
  - hidapi
  - gcc
sources:
  - https://git.sr.ht/~ireas/nitrokey-rs
tasks:
  - build: |
      cd nitrokey-rs
      cargo build --release
  - test: |
      cd nitrokey-rs
      cargo test
  - format: |
      cd nitrokey-rs
      cargo fmt -- --check
triggers:
  - action: email
    condition: failure
    to: nitrokey-rs-dev <nitrokey-rs-dev@ireas.org>
